run:

linters-settings:
  govet:
    check-shadowing: false
    enable:
      - assign
      - atomic
      - bools
      - buildtag
      - cgocall
      - composites
      - copylocks
      - httpresponse
      - loopclosure
      - lostcancel
      - nilfunc
      - printf
      - shift
      - stdmethods
      - structtag
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult
    disable:
      - shadow

linters:
  enable-all: false
  disable:
    # Write linter name if disable

issues:
  exclude-rules:
    # false positive
    - path: jwe/internal/aescbc/aescbc.go
      text: "ineffectual assignment to `n`"
      linters:
        - ineffassign
    - path: internal/concatkdf/concatkdf.go
      text: "ineffectual assignment to `n`"
      linters:
        - ineffassign
    # fix it
    - path: /*\.go
      linters:
        - errcheck # TODO: Error return value of `xxx` is not checked

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

