run:

linters-settings:
  govet:
    check-shadowing: false
    enable:
      - assign
      - atomic
      - bools
      - buildtag
      - cgocall
      - composites
      - copylocks
      - httpresponse
      - loopclosure
      - lostcancel
      - nilfunc
      - printf
      - shift
      - stdmethods
      - structtag
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult
    disable:
      - shadow

linters:
  enable-all: true
  disable:
    - gomnd
    - gocritic
    - lll
    - gochecknoinits
    - wsl
    - nakedret
    - funlen
    - gochecknoglobals
    - gocognit
    - godox
    - gocyclo
    - dupl
    - gosec

issues:
  exclude-rules:
    # false positive
    - path: jwe/internal/aescbc/aescbc.go
      text: "ineffectual assignment to `n`"
      linters:
        - ineffassign
    - path: internal/concatkdf/concatkdf.go
      text: "ineffectual assignment to `n`"
      linters:
        - ineffassign
    # not needed
    - path: /*.go
      text: "ST1003: should not use underscores in package names"
      linters:
        - stylecheck
    - path: /*.go
      text: "don't use an underscore in package name"
      linters:
        - golint
    - path: /*.go
      text: "returns unexported type" # exported func XXX returns unexported type xxx which can be annoying to use
      linters:
        - golint
    - path: /*.go
      text: "don't use leading" # don't use leading k in Go names; const kKey should be key
      linters:
        - golint
    # fix it
    - path: /*.go
      linters:
        - errcheck # TODO: Error return value of `xxx` is not checked

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

