language: go
sudo: false
install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0
script:
  - make generate
  - go test -v ./...
  - golangci-lint run ./...
  - ./scripts/check-diff.sh
go:
    - 1.13.x
    - 1.14.x
    - tip
