name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 'tip', '1.14', '1.13' ]
    name: Go ${{ matrix.go }} test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Go stable version
        if: matrix.go != 'tip'
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Install Go tip
        if: matrix.go == 'tip'
        run: |
          git clone --depth=1 https://go.googlesource.com/go $HOME/gotip
          cd $HOME/gotip/src
          ./make.bash
          export GOROOT=$HOME/gotip
          go env GOPATH
          echo $PATH
          export PATH=$(go env GOPATH)/bin:$HOME/gotip/bin:$PATH
      - name: Install GolangCI-Lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.25.0
      - run: make generate
      - run: make test
      - run: |
          ls /home/runner/go/bin/
          go env GOPATH
          echo $PATH
          make lint
      - name: Check difference between generation code and commit code
        run: make check_diffs

