# Smoke tests only run on non-master branches. Smoke tests cut
# some corners by running selected tests in parallel (to shave off
# some execution time)
# Once a pull request is merged to master, workflows/ci.yml is run
name: Smoke Tests
on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.15', '1.14' ]
    name: Go ${{ matrix.go }} test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install Go stable version
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Install jose
        run: sudo apt-get install -y --no-install-recommends jose
      - run: make generate
      - name: Run smoke tests
        run: make smoke
      - name: Check difference between generation code and commit code
        run: make check_diffs
